loki:
  image:
    registry: docker.io
    repository: bitnami/grafana-loki
    tag: 3.1.1-debian-12-r2
#==========================================
compactor:
  persistence:
    size: 5Gi
indexGateway:
  persistence:
    size: 5Gi
ingester:
  persistence:
    size: 5Gi
querier:
  persistence:
    size: 5Gi
ruler:
  persistence:
    size: 5Gi
#=========================================[ Service Monitor ]
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus-stack
#==========================================
gateway:
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.27.1-debian-12-r2

promtail:
  image:
    registry: docker.io
    repository: bitnami/promtail
    tag: 3.1.1-debian-12-r0

volumePermissions:
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r28
